// Please put date in YYYY-MM-DD format
export const otherPhotos = [
    {
        "name": "Brooklyn Bridge Park",
        "desc": "From left to right: Maggie, Justin, Khandy, Wentao, Corinne",
        "date": "2018-06-1",
	"imgname": "brooklynbridge-0.png",
	"credits": "Khandy",
    },
    {
        "name": "Fire Poi",
        "desc": "An exposure of fire poi.",
        "date": "2019-06-1",
	"imgname": "fire_exposure0.png",
	"credits": "Khandy",
    },
    {
        "name": "Fire Poi",
        "desc": "An exposure of fire poi.",
        "date": "2019-06-1",
	"imgname": "fire_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "Frontal Flowers",
        "desc": "Exposure of frontal flowers.",
        "date": "2019-06-1",
	"imgname": "flower_exposure0.png",
	"credits": "Khandy",
    },
    {
        "name": "Four Petal Antispin Flowers",
        "desc": "Exposure of four petal antispin flowers.",
        "date": "2019-06-1",
	"imgname": "flower_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "Four Petal Antispin Flowers",
        "desc": "Exposure of four petal antispin flowers. Probably Matthew.",
        "date": "2019-06-1",
	"imgname": "flower_exposure2.png",
	"credits": "Khandy",
    },
    {
        "name": "Antispin Flowers",
        "desc": "Exposure of antispin flowers.",
        "date": "2019-06-1",
	"imgname": "flower_exposure3.png",
	"credits": "Khandy",
    },
    {
        "name": "Four Petal Antispin Flowers",
        "desc": "Exposure of four petal antispin flowers.",
        "date": "2019-06-1",
	"imgname": "flower_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "<3",
        "desc": "Heart exposure.",
        "date": "2019-06-1",
	"imgname": "heart_exposure.png",
	"credits": "Khandy",
    },
    {
        "name": "<3",
        "desc": "Heart exposure.",
        "date": "2019-06-1",
	"imgname": "heart_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "<3",
        "desc": "Heart exposure.",
        "date": "2019-06-1",
	"imgname": "heart_exposure.png",
	"credits": "Khandy",
    },
    {
        "name": "Bowtie",
        "desc": "Heiley doing a bowtie orbital.",
        "date": "2018-08-1",
	"imgname": "bowtie.png",
	"credits": "Khandy",
    },
    {
        "name": "Flip-Flop",
        "desc": "Vivian H.",
        "date": "2020-01-1",
	"imgname": "some_exposure.png",
	"credits": "Khandy",
    },
    {
        "name": "Circle",
        "desc": "An exposure of someone doing a circle.",
        "date": "2018-06-1",
	"imgname": "some_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "Circle",
        "desc": "An exposure of someone doing a circle.",
        "date": "2018-06-1",
	"imgname": "some_exposure2.png",
	"credits": "Khandy",
    },
    {
        "name": "Spirals",
        "desc": "Finally, a move Alice can recognize. Probably Matthew.",
        "date": "2019-06-1",
	"imgname": "spiral_exposure0.png",
	"credits": "Khandy",
    },
    {
        "name": "Star",
        "desc": "Star exposure.",
        "date": "2018-06-1",
	"imgname": "star_exposure.png",
	"credits": "Khandy",
    },
    {
        "name": "Random",
        "desc": "A random exposure.",
        "date": "2018-06-31",
	"imgname": "random_exposure.png",
	"credits": "Khandy",
    },
    {
        "name": "Random",
        "desc": "A random exposure. Jason points out it might be a failed attempt at words.",
        "date": "2018-06-31",
	"imgname": "random_exposure1.png",
	"credits": "Khandy",
    },
    {
        "name": "Whip Light",
        "desc": "Exposure taken of a whip light.",
        "date": "2018-06-31",
	"imgname": "whip_exposure0.png",
	"credits": "Khandy",
    },
    {
        "name": "FlowVid-19",
        "desc": "Our StuySquad performance for FlowVid-19!",
        "date": "2020-06-10",
	"imgname": "flowvid-19.png",
	"credits": "Khandy",
    },
    {
        "name": "Handy Dandy Steve Guide",
        "desc": "Masterpiece by Vivian Y. Handy dandy for knowing how to space yourself on stage.",
        "date": "2018-06-31",
	"imgname": "steve_guide.png",
	"credits": "Vivian Y.",
    },
    {
        "name": "Whip Light",
        "desc": "Exposure taken of a whip light.",
        "date": "2018-06-31",
	"imgname": "whip_exposure0.png",
	"credits": "Khandy",
    },
    {
        "name": "Goodbye Shiho",
        "desc": "Goodbye studio for tiniest flower Shiho.",
        "date": "2019-07-05",
	"imgname": "studio-07052019.png",
	"credits": "Khandy",
    },
    
]
